/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But we want to manually specify the sidebar for more control
  docs: [
    'about',
    {
      type: 'category',
      label: '🛠️ Configuration',
      // collapsed: false,
      collapsible: false,
      items: [
        {
          type: 'link',
          href: '/llms',
          label: 'LLMs',
          className: 'category-sublink',
        },
        {
          type: 'link',
          href: '/embedders',
          label: 'Embedding Models',
          className: 'category-sublink',
        },
        {
          type: 'link',
          href: '/vector-databases',
          label: 'Vector Databases',
          className: 'category-sublink',
        },
      ]
    },
  ],
  llms: [
    {
      type: 'link',
      label: '← Home',
      href: '/'
    },
    'llms',
    {
      type: 'category',
      label: 'Local LLM Providers',
      collapsed: false,
      className: 'category-header',
      items: [
        'llms/desktop-built-in',
        'llms/ollama',
        'llms/lmstudio',
        'llms/localai',
      ],
    },
    {
      type: 'category',
      label: 'Cloud-LLM Providers',
      collapsed: false,
      className: 'category-header',
      items: [
        'llms/openai',
        'llms/azure-openai',
        'llms/anthropic',
        'llms/google-gemini',
        'llms/together-ai',
        'llms/openrouter',
        'llms/hugging-face',
        'llms/mistral',
        'llms/perplexity',
        'llms/groq',
        'llms/generic-openai',
      ],
    },
  ],
  embedders: [
    {
      type: 'link',
      label: '← Home',
      href: '/'
    },
    'embedders',
    {
      type: 'category',
      label: 'Local Embedding Providers',
      collapsed: false,
      className: 'category-header',
      items: [
        'embedders/built-in',
        'embedders/ollama',
        'embedders/lmstudio',
        'embedders/localai',
      ],
    },
    {
      type: 'category',
      label: 'Cloud-Embedding Providers',
      collapsed: false,
      className: 'category-header',
      items: [
        'embedders/openai',
        'embedders/azure-openai',
      ],
    },
  ],
  "vector-databases": [
    {
      type: 'link',
      label: '← Home',
      href: '/'
    },
    'vector-databases',
    {
      type: 'category',
      label: 'Local vector databases',
      collapsed: false,
      className: 'category-header',
      items: [
        'vector-databases/lancedb',
        'vector-databases/chromadb',
        {
          type: 'link',
          label: 'Milvus',
          href: 'https://github.com/milvus-io/milvus',
          className: 'category-external-link'
        }
      ],
    },
    {
      type: 'category',
      label: 'Cloud Vector Databases',
      collapsed: false,
      className: 'category-header',
      items: [
        {
          type: 'link',
          label: 'Pinecone',
          href: 'https://www.pinecone.io/',
          className: 'category-external-link'
        },
        {
          type: 'link',
          label: 'QDrant',
          href: 'https://qdrant.tech/',
          className: 'category-external-link'
        },
        {
          type: 'link',
          label: 'AstraDB',
          href: 'https://www.datastax.com/',
          className: 'category-external-link'
        },
        {
          type: 'link',
          label: 'Zilliz',
          href: 'https://zilliz.com/',
          className: 'category-external-link'
        },
        {
          type: 'link',
          label: 'Weaviate',
          href: 'https://weaviate.io/',
          className: 'category-external-link'
        },
      ],
    },
  ],
};

module.exports = sidebars;
